theme = "pehtheme-hugo"
baseURL = "https://horstmayer1984-debug.github.io/ai-tools-vergleich/"
defaultContentLanguage = "de"

enableRobotsTXT = true
summaryLength = 25

buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 12

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]
