# -- Theme Parameters --
# Minimalistisches, seri√∂ses Design

colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = false

enableA11y = false
enableSearch = false
enableCodeCopy = true
enableStructuredBreadcrumbs = false
enableCookieConsent = false
replyByEmail = false

mainSections = ["posts", "vergleiche", "reviews"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

# Keine Hintergrundbilder
defaultBackgroundImage = ""
defaultFeaturedImage = ""
defaultSocialImage = ""
hotlinkFeatureImage = false

highlightCurrentMenuArea = false
smartTOC = true
smartTOCHideUnfocusedChildren = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page"
  showRecent = true
  showRecentItems = 50
  showMoreLink = false
  showMoreLinkDest = ""
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  showHero = false
  heroStyle = "basic"
  layoutBackgroundBlur = false
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  relatedContentLimit = 0
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = false
  sharingLinks = []
  showZenMode = false

[list]
  showHero = false
  heroStyle = "basic"
  layoutBackgroundBlur = false
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = false
  heroStyle = "basic"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  heroStyle = "basic"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[firebase]
  apiKey = ""
  authDomain = ""
  projectId = ""
  storageBucket = ""
  messagingSenderId = ""
  appId = ""
  measurementId = ""

[buymeacoffee]
  identifier = ""
  globalWidget = false

[verification]

[rssnext]

[advertisement]

[params.custom]
  css = ["css/custom.css"]

[privacy]
  disablePrivacySettings = true
